apiVersion: apps/v1
kind: Deployment
metadata:
  name: employees
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: employee-container
          image: employee-image
          imagePullPolicy: Never
          ports:
            - containerPort: 80